[tools]
wally = { source = "UpliftGames/wally", version = "0.2.1" }
luau-analyze = { source = "JohnnyMorganz/luau-analyze-rojo", version = "0.525.2" }
makers-test = { source = "sagiegurari/cargo-make", version = "0.32.12" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }